version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dommus/app
    container_name: dommus-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - dommus

  db:
    image: mysql:8.0
    container_name: dommus-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - dommus
    ports:
      - "3306:3306"

  nginx:
    image: nginx:1.23-alpine
    container_name: dommus-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - dommus

networks:
  dommus:
    driver: bridge

volumes:
  dbdata:
    driver: local